#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III

bspc config border_width         4
bspc config window_gap           10

bspc config split_ratio				0.5
bspc config single_monocle			false
bspc config focus_follows_pointer	true
bspc config borderless_monocle		true
bspc config gapless_monocle			true

bspc config presel_feedback_color "#9e5671"
bspc config active_border_color		"#a88b98"
bspc config focused_border_color "#d69cc1"
bspc config normal_border_color "#846a78"

#bspc rule -a "*" split_dir=east
#bspc rule -a \* rectangle 1280x720+0+0 center=true

# Auto Start
sxhkd &
picom --config $HOME/.config/picom/picom.conf &
nitrogen --restore &
dunst &
polybar &
